function [x,y] = coordTransform(i, j, angle, newX, newY, X, Y)
    midX = floor(newX/2);
    midY = floor(newY/2);
    x0 = floor(X/2);
    y0 = floor(Y/2);
    R = [cosd(angle) sind(angle) 0; ...
        -sind(angle) cosd(angle) 0; ...
        0 0 1];
    T1 = [1 0 x0;...
          0 1 y0;...
          0 0 1];
    T2= [1 0 -midX;...
         0 1 -midY;...
         0 0 1];

    oldPixelPos = T1*R*T2*[i;j;1];
    x = floor(oldPixelPos(1));
    y = floor(oldPixelPos(2));
end